services:
  jboss:
    image: quay.io/wildfly/wildfly
    container_name: jboss
    ports:
      - 8080:8080
    volumes:
      - ./target:/opt/jboss/wildfly/standalone/deployments/

  mysqldb:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: mypack
      MYSQL_PASSWORD: 123456789
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - mysqldb
    environment:
       PMA_HOST: mysqldb
       PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80

volumes:
  dbdata:


