services:
  jboss:
    image: quay.io/wildfly/wildfly
    container_name: jboss
    ports:
      - 80:8080
    volumes:
      - ./target/MyPack-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: mypack
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - C:\data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    depends_on:
      - mysqldb
    environment:
       PMA_HOST: mysqldb
       PMA_PORT: 3306
       PMA_USER: root
       PMA_PASSWORD: 123456789
    restart: always
    ports:
      - 8081:80